language: python
python:
  - "3.5.2"
# command to install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install -r requirements/common.txt
# command to run tests
script:
  - ./run_tests.sh
